TEXT_ALL = {}

TEXT_ALL["ru"] = {
    "m_n": "Бот биржи PrizmBit",
    "m_a": "Бот биржи PrizmBit",
    "m_b1": "📈 Торги",
    "m_b2": "💼 Кошелек",
    "m_b3": "⚙️ Настройки",
    "t": "📈 <b>Торги</b>\n\n%s",
    "t_sp": "<b>%s: %s</b>\n\n📊 <b>Статистика 24 часа:</b>\nlow: %s\nhigh: %s\nvolume: %s\nchange: %s\n\n<b>Состояние стакана на текущий момент:</b>\n\n📉 Продажа(Ask)\n<code>Цена           Количество\n%s</code>\n\n📈 Покупка(Bid)\n<code>%s</code>",
    "t_sp_b1": "🔄 Обновить",
    "t_sp_b1_answer": "Данные обновлены!",
    "t_sp_b2": "➕ Создать ордер",
    "t_sp_b3": "🏷 Мои ордера",
    "t_sp_b4": "🗄 Мои трейды",
    "t_sp_b5": "📈 График",
    "t_sp_graph": "📈 График %s",
    "t_sp_co": "<b>Создание %s ордера</b>",
    "t_sp_co_b1": "📈 Купить",
    "t_sp_co_b2": "📉 Продать",
    "t_sp_co_b3": "⚙️ Тип: %s",
    "t_sp_co_b5": "✅ Далее",
    "t_sp_co1": "Введите размер ордера",
    "t_sp_co2": "Введите цену",
    "t_sp_co3": "Введите стоп-цену",
    "t_sp_co4": "Введите лимит-цену",
    "t_sp_co5": "✅ Ордер создан",
    "t_sp_co_e1": "Выберите направление Купить/Продать",
    "t_sp_co_e2": "✖️ Неверный ввод. Введите число в формате 12.345",
    "t_sp_mo": "🏷 Мои ордера %s",
    "t_sp_mo1": "🏷 Нет открытых ордеров %s",
    "t_sp_mo_1": "Цена",
    "t_sp_mo_2": "Стоп-цена",
    "t_sp_mo_3": "Лимит-цена",
    "t_sp_mo_c": "Ордер %i отменен.",
    "t_sp_mo_b1": "✖️ Отменить все",
    "t_sp_mo_b1_": "✖️ Все ордера отменены",
    "t_sp_mo_row": "   -  ID: %i %s %s %s",
    "t_sp_mo_buy": "Покупка",
    "t_sp_mo_sell": "Продажа",
    "t_sp_mt": "🗄 Мои трейды %s",
    "t_sp_mt1": "🗄 Нет %s трейдов",
    "t_sp_mt_buy": "Покупка",
    "t_sp_mt_sell": "Продажа",
    "t_sp_mt_row": "   %i.  %s %s %s %s",
    "w": "💼 <b>Кошелек</b>\n%s",
    "w2": "Аккаунт:",
    "w_b1": "📥 Пополнить",
    "w_b1_1": "Выберите валюту для пополнения",
    "w_b1_b2t": "✅ Сгенерировать новый",
    "w_b1_b2f": "❎ Сгенерировать новый",
    "w_b1__": "Адрес для пополнения:",
    "w_b2": "📤 Отправить",
    "w_b3": "🔁 Обменять",
    "w_b4": "🕑 История",
    "w_b2_": "Выбери ниже",
    "w_b2_b1": "Отправить на адрес",
    "w_b2_b1_1": "Выбери валюту",
    "w_b2_b1_2": "Введи адрес",
    "w_b2_b1_3": "Введи кол-во",
    "w_b2_b1_4": "Введи описание перевода или 0 чтобы пропустить",
    "w_b2_b1_invalid": "Неправильный ввод",
    "w_b2_b1_invalid2": "Ошибка. Проверь правильность введенных данных.",
    "w_b2_b1_ok": "✅ Перевод создан. Статус: %s",
    "w_b2_b2": "Создать код",
    "w_b2_b2_1": "Выбери валюту",
    "w_b2_b2_2": "Введи кол-во",
    "w_b2_b2_3": "Введи никнейм получателя или 0, чтобы пропустить.",
    "w_b2_b2_4": "Введи описание или 0 чтобы пропустить",
    "w_b2_b2_invalid": "Неправильный ввод",
    "w_b2_b2_invalid2": "Ошибка. Проверь правильность введенных данных.",
    "w_b2_b2_ne": "Недостаточно средств.",
    "w_b2_b2_ok": "✅ Код создан: %s",
    "w_b4_": "Выбери ниже",
    "w_b4_b1": "🕑 Транзакции",
    "w_b4_b2": "🕑 Трейды",
    "w_b4_b3": "🕑 Адреса",
    "w_b4_b4": "🕑 Коды",
    "w_th": "🕑 История транзакций\n\n%s",
    "w_th1": "Вы пока не совершили ни одной транзакции.",
    "w_th_row": "   %i.  %s %s %s %s",
    "s": "⚙️ Настройки",
    "s_b1": "🇷🇺 Язык",
    "s_b1_": "Выбери язык",
    "s_b2": "👤 Привязка/Смена аккаунта",
    "s_b3": "💁‍♂️ Верификация",
    "s_b3_": "Пришли данные в формате:\n\n<code>First Name\nLast Name\nMiddle Name\nBirthdate\nCitizenship\nCountry\nCity\nAddress\nPostal Code\nID Number\nID Expire Date\nID Issue Date</code>",
    "s_b3_1": "Отправь фото паспорта.",
    "s_b3_2": "Отправь фото, удостоверяющее адрес.",
    "s_b3_3": "Отправь селфи.",
    "s_b3_invalid": "Не удалось распознать формат даты: %s",
    "s_b3__": "Данные верификации отправлены на проверку",
    "list_address_row": "   %i.  %s %s %s",
    "list_page": "Страница: ",
    "list_f00": "🕑 Показаны все результаты",
    "list_f01": "🕑 Показаны результаты до %s. Введи \"-\" для отмены",
    "list_f10": "🕑 Показаны результаты с %s. Введи \"-\" для отмены",
    "list_f11": "🕑 Показаны результаты с %s по %s. Введи \"-\" для отмены",
    "list_transaction": "🕑 Транзакции:",
    "list_transaction_ne": "🕑 Транзакций нет",
    "list_trade": "🕑 Трейды:",
    "list_trade_ne": "🕑 Трейдов нет",
    "list_trade1": "🗄 Трейды %s:",
    "list_trade1_ne": "🗄 Трейдов %s нет",
    "list_address": "🕑 Адреса:",
    "list_address_ne": "🕑 Адресов нет",
    "list_code": "🕑 Коды",
    "list_code_ne": "🕑 Кодов нет",
    "back_btn": "< Назад",
    "cancel_btn": "< Отмена",
    "canceled": "Отмена",
    "redeem_code": "Код принят.",
    "loading": "Загрузка...",
    "api_error": "Ошибка в API. Попробуйте позже. Текст ошибки: %s"
}


TEXT_ALL["en"] = {
    "m_n": "Bot of PrizmBit exchange",
    "m_a": "Bot of PrizmBit exchange",
    "m_b1": "📈 Exchange",
    "m_b2": "💼 Wallet",
    "m_b3": "⚙️ Settings",
    "t": "📈 <b>Exchange</b>\n\n%s",
    "t_sp": "<b>%s: %s</b>\n\n📊 <b>Statistics 24 hour:</b>\nlow: %s\nhigh: %s\nvolume: %s\nchange: %s\n\n<b>Order Book:</b>\n\n📈 Ask (%s Buyers orders)\n<code>Price          Amount\n%s</code>\n\n📉 Bid (%s Sellers orders)\n<code>%s</code>",
    "t_sp_b1": "🔄 Refresh",
    "t_sp_b1_answer": "Data updated!",
    "t_sp_b2": "➕ New order",
    "t_sp_b3": "🏷 My orders",
    "t_sp_b4": "🗄 My trades",
    "t_sp_b5": "📈 Chart",
    "t_sp_graph": "📈 Chart %s",
    "t_sp_co": "<b>Create %s order</b>",
    "t_sp_co_b1": "📈 Buy",
    "t_sp_co_b2": "📉 Sell",
    "t_sp_co_b3": "⚙️ Type: %s",
    "t_sp_co_b5": "✅ Next",
    "t_sp_co1": "Enter order amount",
    "t_sp_co2": "Enter price",
    "t_sp_co3": "Enter stop-price",
    "t_sp_co4": "Enter limit-price",
    "t_sp_co5": "✅ Order created",
    "t_sp_co_e1": "Choose Buy or Sell",
    "t_sp_co_e2": "✖️ Wrong input. Enter number, such as 12.345",
    "t_sp_mo": "🏷 My orders %s",
    "t_sp_mo1": "🏷 No open orders %s",
    "t_sp_mo_1": "Price",
    "t_sp_mo_2": "Stop-Price",
    "t_sp_mo_3": "Limit-Price",
    "t_sp_mo_c": "Order %i canceled.",
    "t_sp_mo_b1": "✖️ Cancel all",
    "t_sp_mo_b1_": "✖️ All orders canceled",
    "t_sp_mo_row": "   -  ID: %i %s %s %s",
    "t_sp_mo_buy": "Buy",
    "t_sp_mo_sell": "Sell",
    "t_sp_mt": "🗄 My trades %s",
    "t_sp_mt1": "🗄 No %s trades",
    "t_sp_mt_buy": "Buy",
    "t_sp_mt_sell": "Sell",
    "t_sp_mt_row": "   %i.  %s %s %s %s",
    "w": "💼 <b>Wallet</b>\n%s",
    "w2": "Account:",
    "w_b1": "📥 Recieve",
    "w_b1_1": "Choose currency",
    "w_b1_b2t": "✅ Generate new",
    "w_b1_b2f": "❎ Generate new",
    "w_b1__": "Address:",
    "w_b2": "📤 Send",
    "w_b3": "🔁 Exchange",
    "w_b4": "🕑 History",
    "w_b2_": "Choose variant",
    "w_b2_b1": "Send to address",
    "w_b2_b1_1": "Choose currency",
    "w_b2_b1_2": "Enter address",
    "w_b2_b1_3": "Enter amount",
    "w_b2_b1_4": "Enter some description or 0 to skip",
    "w_b2_b1_invalid": "Wrong input",
    "w_b2_b1_invalid2": "Error. Check if provided data is correct.",
    "w_b2_b1_ok": "✅ Transfer created. Status: %s",
    "w_b2_b2": "Create code",
    "w_b2_b2_1": "Choose currency",
    "w_b2_b2_2": "Enter amount",
    "w_b2_b2_3": "Enter recipient nickname or 0 to skip",
    "w_b2_b2_4": "Enter some description or 0 to skip",
    "w_b2_b2_invalid": "Wrong input",
    "w_b2_b2_invalid2": "Error. Check if provided data is correct.",
    "w_b2_b2_ne": "Insufficient funds",
    "w_b2_b2_ok": "✅ Code created: %s",
    "w_b4_": "Choose variant",
    "w_b4_b1": "🕑 Transactions",
    "w_b4_b2": "🕑 Trades",
    "w_b4_b3": "🕑 Addresses",
    "w_b4_b4": "🕑 Codes",
    "w_th": "🕑 Transaction history\n\n%s",
    "w_th1": "No transactions yet.",
    "w_th_row": "   %i.  %s %s %s %s",
    "s": "⚙️ Settings",
    "s_b1": "🇷🇺 Language",
    "s_b1_": "Choose bot language",
    "s_b2": "👤 Link/Unlink account",
    "s_b3": "💁‍♂️ Verification",
    "s_b3_": "Send data in such format:\n\n<code>First Name\nLast Name\nMiddle Name\nBirthdate\nCitizenship\nCountry\nCity\nAddress\nPostal Code\nID Number\nID Expire Date\nID Issue Date</code>",
    "s_b3_1": "Send ID photo.",
    "s_b3_2": "Send address proof photo",
    "s_b3_3": "Send your selfie",
    "s_b3_invalid": "Wrong date format: %s",
    "s_b3__": "Verification data has been sent for review",
    "list_address_row": "   %i.  %s %s %s",
    "list_page": "Page: ",
    "list_f00": "🕑 Showing all results",
    "list_f01": "🕑 Showing results until %s. Send \"-\" to cancel",
    "list_f10": "🕑 Showing results from %s. Send \"-\" to cancel",
    "list_f11": "🕑 Showing results from %s to %s. Send \"-\" to cancel",
    "list_transaction": "🕑 Transactions:",
    "list_transaction_ne": "🕑 No transactions",
    "list_trade": "🕑 Trades:",
    "list_trade_ne": "🕑 No trades",
    "list_trade1": "🗄 Trades %s:",
    "list_trade1_ne": "🗄 No %s trades",
    "list_address": "🕑 Addresses:",
    "list_address_ne": "🕑 No addresses",
    "list_code": "🕑 Codes:",
    "list_code_ne": "🕑 No codes",
    "back_btn": "< Back",
    "cancel_btn": "< Cancel",
    "canceled": "Canceled",
    "redeem_code": "Code accepted.",
    "loading": "Loading...",
    "api_error": "Api error. Try again later. Error text: %s"
}

_keys = list(TEXT_ALL.keys())
for i in range(len(_keys) - 1):
	diff = set(TEXT_ALL[_keys[i]]) ^ set(TEXT_ALL[_keys[i+1]])
	if len(diff) != 0:
		raise Exception("Not simmilar text_data keys set! Missing: " + ", ".join(list(diff)))
