# Generated by Django 2.1.7 on 2019-02-13 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True, verbose_name='Telegram id')),
                ('name', models.CharField(max_length=300, verbose_name='Name from Telegram')),
                ('status', models.CharField(choices=[('m', 'Main')], default='m', max_length=2, verbose_name='Status In Chat')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active in Telegram')),
                ('last_active', models.DateTimeField(auto_now=True, verbose_name='Last Active')),
                ('date_registered', models.DateTimeField(auto_now_add=True, verbose_name='Registered')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
